baseURL = "https://example.com/"
languageCode = "zh-cn"
title = "我的博客"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  defaultTheme = "auto"
